//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction_BD.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Auction_BDEntities : DbContext
    {
        public Auction_BDEntities()
            : base("name=Auction_BDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admins { get; set; }
        public DbSet<cetagory> cetagories { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<user> users { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
