//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Auction_BD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int pro_id { get; set; }
        public string pro_name { get; set; }
        public string pro_iamge { get; set; }
        public int pro_price { get; set; }
        public string pro_des { get; set; }
        public Nullable<int> pro_fk_cat { get; set; }
        public Nullable<int> pro_fk_user { get; set; }
        public Nullable<int> bid_price { get; set; }
        public Nullable<int> aprv { get; set; }
        public Nullable<int> u_id { get; set; }
        public Nullable<System.DateTime> date_of_post { get; set; }
    
        public virtual cetagory cetagory { get; set; }
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
